CREATE TABLE IF NOT EXISTS public.fligths
(
    id integer NOT NULL DEFAULT nextval('fligths_id_seq'::regclass),
    callsign character varying(10) COLLATE pg_catalog."default",
    matricula character varying(10) COLLATE pg_catalog."default",
    tipo_aeronave character varying(10) COLLATE pg_catalog."default",
    empresa character varying(50) COLLATE pg_catalog."default",
    numero_vuelo integer,
    tipo_vuelo character varying(1) COLLATE pg_catalog."default",
    tiempo_inicial timestamp without time zone,
    origen character varying(10) COLLATE pg_catalog."default",
    pista_origen character varying(10) COLLATE pg_catalog."default",
    sid character varying(10) COLLATE pg_catalog."default",
    fecha_salida date,
    hora_salida time without time zone,
    destino character varying(10) COLLATE pg_catalog."default",
    pista_destino character varying(10) COLLATE pg_catalog."default",
    fecha_llegada date,
    hora_llegada time without time zone,
    nivel integer,
    ambito character varying(1) COLLATE pg_catalog."default",
    nombre_origen character varying(100) COLLATE pg_catalog."default",
    nombre_destino character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT fligths_pkey PRIMARY KEY (id)
)
