# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import copy_metadata, collect_submodules

block_cipher = None

datas = [
    ('web/dist', 'web/dist'),
    ('src', 'src'),
]
datas += copy_metadata('duckdb')
datas += copy_metadata('pandas')
datas += copy_metadata('numpy')
datas += copy_metadata('scikit-learn')
datas += copy_metadata('matplotlib')

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=[
        'sklearn.tree._partitioner',
        'sklearn.tree._utils',
        'sklearn.utils._cython_blas',
        'sklearn.utils._typedefs',
        'sklearn.neighbors._typedefs',
        'sklearn.neighbors._quad_tree',
        'sklearn.tree._criterion',
        'sklearn.tree._splitter',
        'sklearn.tree',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'engineio.async_drivers.asgi',
        'duckdb',
        'pandas',
        'openpyxl',
        'python_multipart',
        'dependency_injector.errors',
        'dependency_injector.containers',
        'dependency_injector.providers',
        'dependency_injector.wiring',
        'matplotlib',
        'reportlab',
        'polars',
        'squarify',
        'fastapi',
        'starlette',
        'pydantic',
        'pydantic_settings',
        'anyio',
        'httpx',
        'httpcore',
        'h11',
        'httptools',
        'websockets',
        'click',
        'colorama',
        'certifi',
        'idna',
        'numpy',
        'PIL',
        'yaml',
        'dateutil',
        'dotenv',
        'six',
        'typing_extensions',
        'packaging',
        'fonttools',
        'kiwisolver',
        'cycler',
        'contourpy',
        'et_xmlfile',
        'jaraco.text',
        'jaraco.functools',
        'jaraco.context',
        'more_itertools',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'PyQt5', 'notebook', 'ipython', 'nbconvert', 'jedi'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ATC_Capacity_Calculator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
